serviceName: api_gateway_service
http:
  port: :5001
  development: true
  basePath: /api/v1
  todosPath: /api/v1/todos
  debugHeaders: false
  httpClientDebug: false
  debugErrorsResponse: true
  ignoreLogUrls: [ "metrics" ]
logger:
  level: debug
  devMode: false
  encoder: console #or json
kafka:
  brokers: [ "localhost:9092" ]
  groupID: api_gateway_consumer
  initTopics: true
kafkaTopics:
  todoCreate:
    topicName: todo_create
    partitions: 10
    replicationFactor: 1
  todoUpdate:
    topicName: todo_update
    partitions: 10
    replicationFactor: 1
  todoDelete:
    topicName: todo_delete
    partitions: 10
    replicationFactor: 1
